version: '2'
services:
  tester:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - selenium
    environment:
      - SELENIUM_REMOTE_URL="http://selenium:4444/wd/hub"

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"